info:
  title: Assistants
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
openapi: 3.0.1
paths:
  /understand/Assistants/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Assistants
        - Sid
    post:
      description: ''
      tags:
        - Assistants
        - Sid
    delete:
      description: ''
      tags:
        - Assistants
        - Sid
  /understand/Assistants/{AssistantSid}/FallbackActions:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Assistants
        - Sid
        - Assistant
        - Fallback
        - Actions
    post:
      description: ''
      tags:
        - Assistants
        - Sid
        - Assistant
        - Fallback
        - Actions
  /understand/Assistants/{AssistantSid}/InitiationActions:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Assistants
        - Sid
        - Assistant
        - Fallback
        - Actions
        - Initiation
    post:
      description: ''
      tags:
        - Assistants
        - Sid
        - Assistant
        - Fallback
        - Actions
        - Initiation
  /understand/Assistants/{AssistantSid}/Dialogues/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Assistants
        - Sid
        - Assistant
        - Fallback
        - Actions
        - Initiation
        - Dialogues
  /understand/Assistants/{AssistantSid}/Tasks/{TaskSid}/Fields/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Assistants
        - Sid
        - Assistant
        - Fallback
        - Actions
        - Initiation
        - Dialogues
        - Tasks
        - Task
        - Fields
    delete:
      description: ''
      tags:
        - Assistants
        - Sid
        - Assistant
        - Fallback
        - Actions
        - Initiation
        - Dialogues
        - Tasks
        - Task
        - Fields
  /understand/Assistants/{AssistantSid}/Tasks/{TaskSid}/Fields:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Assistants
        - Sid
        - Assistant
        - Fallback
        - Actions
        - Initiation
        - Dialogues
        - Tasks
        - Task
        - Fields
    post:
      description: ''
      tags:
        - Assistants
        - Sid
        - Assistant
        - Fallback
        - Actions
        - Initiation
        - Dialogues
        - Tasks
        - Task
        - Fields
  /understand/Assistants/{AssistantSid}/FieldTypes/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Assistants
        - Sid
        - Assistant
        - Fallback
        - Actions
        - Initiation
        - Dialogues
        - Tasks
        - Task
        - Fields
        - Field
        - Types
    post:
      description: ''
      tags:
        - Assistants
        - Sid
        - Assistant
        - Fallback
        - Actions
        - Initiation
        - Dialogues
        - Tasks
        - Task
        - Fields
        - Field
        - Types
    delete:
      description: ''
      tags:
        - Assistants
        - Sid
        - Assistant
        - Fallback
        - Actions
        - Initiation
        - Dialogues
        - Tasks
        - Task
        - Fields
        - Field
        - Types
  /understand/Assistants/{AssistantSid}/FieldTypes:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Assistants
        - Sid
        - Assistant
        - Fallback
        - Actions
        - Initiation
        - Dialogues
        - Tasks
        - Task
        - Fields
        - Field
        - Types
    post:
      description: ''
      tags:
        - Assistants
        - Sid
        - Assistant
        - Fallback
        - Actions
        - Initiation
        - Dialogues
        - Tasks
        - Task
        - Fields
        - Field
        - Types
  /understand/Assistants/{AssistantSid}/FieldTypes/{FieldTypeSid}/FieldValues/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Assistants
        - Sid
        - Assistant
        - Fallback
        - Actions
        - Initiation
        - Dialogues
        - Tasks
        - Task
        - Fields
        - Field
        - Types
        - Type
        - Values
    delete:
      description: ''
      tags:
        - Assistants
        - Sid
        - Assistant
        - Fallback
        - Actions
        - Initiation
        - Dialogues
        - Tasks
        - Task
        - Fields
        - Field
        - Types
        - Type
        - Values
  /understand/Assistants/{AssistantSid}/FieldTypes/{FieldTypeSid}/FieldValues:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Assistants
        - Sid
        - Assistant
        - Fallback
        - Actions
        - Initiation
        - Dialogues
        - Tasks
        - Task
        - Fields
        - Field
        - Types
        - Type
        - Values
    post:
      description: ''
      tags:
        - Assistants
        - Sid
        - Assistant
        - Fallback
        - Actions
        - Initiation
        - Dialogues
        - Tasks
        - Task
        - Fields
        - Field
        - Types
        - Type
        - Values
  /understand/Assistants/{AssistantSid}/ModelBuilds/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Assistants
        - Sid
        - Assistant
        - Fallback
        - Actions
        - Initiation
        - Dialogues
        - Tasks
        - Task
        - Fields
        - Field
        - Types
        - Type
        - Values
        - Model
        - Builds
    post:
      description: ''
      tags:
        - Assistants
        - Sid
        - Assistant
        - Fallback
        - Actions
        - Initiation
        - Dialogues
        - Tasks
        - Task
        - Fields
        - Field
        - Types
        - Type
        - Values
        - Model
        - Builds
    delete:
      description: ''
      tags:
        - Assistants
        - Sid
        - Assistant
        - Fallback
        - Actions
        - Initiation
        - Dialogues
        - Tasks
        - Task
        - Fields
        - Field
        - Types
        - Type
        - Values
        - Model
        - Builds
  /understand/Assistants/{AssistantSid}/ModelBuilds:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Assistants
        - Sid
        - Assistant
        - Fallback
        - Actions
        - Initiation
        - Dialogues
        - Tasks
        - Task
        - Fields
        - Field
        - Types
        - Type
        - Values
        - Model
        - Builds
    post:
      description: ''
      tags:
        - Assistants
        - Sid
        - Assistant
        - Fallback
        - Actions
        - Initiation
        - Dialogues
        - Tasks
        - Task
        - Fields
        - Field
        - Types
        - Type
        - Values
        - Model
        - Builds
  /understand/Assistants/{AssistantSid}/Queries/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Assistants
        - Sid
        - Assistant
        - Fallback
        - Actions
        - Initiation
        - Dialogues
        - Tasks
        - Task
        - Fields
        - Field
        - Types
        - Type
        - Values
        - Model
        - Builds
        - Queries
    post:
      description: ''
      tags:
        - Assistants
        - Sid
        - Assistant
        - Fallback
        - Actions
        - Initiation
        - Dialogues
        - Tasks
        - Task
        - Fields
        - Field
        - Types
        - Type
        - Values
        - Model
        - Builds
        - Queries
    delete:
      description: ''
      tags:
        - Assistants
        - Sid
        - Assistant
        - Fallback
        - Actions
        - Initiation
        - Dialogues
        - Tasks
        - Task
        - Fields
        - Field
        - Types
        - Type
        - Values
        - Model
        - Builds
        - Queries
  /understand/Assistants/{AssistantSid}/Queries:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Assistants
        - Sid
        - Assistant
        - Fallback
        - Actions
        - Initiation
        - Dialogues
        - Tasks
        - Task
        - Fields
        - Field
        - Types
        - Type
        - Values
        - Model
        - Builds
        - Queries
    post:
      description: ''
      tags:
        - Assistants
        - Sid
        - Assistant
        - Fallback
        - Actions
        - Initiation
        - Dialogues
        - Tasks
        - Task
        - Fields
        - Field
        - Types
        - Type
        - Values
        - Model
        - Builds
        - Queries
  /understand/Assistants/{AssistantSid}/Tasks/{TaskSid}/Samples/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Assistants
        - Sid
        - Assistant
        - Fallback
        - Actions
        - Initiation
        - Dialogues
        - Tasks
        - Task
        - Fields
        - Field
        - Types
        - Type
        - Values
        - Model
        - Builds
        - Queries
        - Samples
    post:
      description: ''
      tags:
        - Assistants
        - Sid
        - Assistant
        - Fallback
        - Actions
        - Initiation
        - Dialogues
        - Tasks
        - Task
        - Fields
        - Field
        - Types
        - Type
        - Values
        - Model
        - Builds
        - Queries
        - Samples
    delete:
      description: ''
      tags:
        - Assistants
        - Sid
        - Assistant
        - Fallback
        - Actions
        - Initiation
        - Dialogues
        - Tasks
        - Task
        - Fields
        - Field
        - Types
        - Type
        - Values
        - Model
        - Builds
        - Queries
        - Samples
  /understand/Assistants/{AssistantSid}/Tasks/{TaskSid}/Samples:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Assistants
        - Sid
        - Assistant
        - Fallback
        - Actions
        - Initiation
        - Dialogues
        - Tasks
        - Task
        - Fields
        - Field
        - Types
        - Type
        - Values
        - Model
        - Builds
        - Queries
        - Samples
    post:
      description: ''
      tags:
        - Assistants
        - Sid
        - Assistant
        - Fallback
        - Actions
        - Initiation
        - Dialogues
        - Tasks
        - Task
        - Fields
        - Field
        - Types
        - Type
        - Values
        - Model
        - Builds
        - Queries
        - Samples
  /understand/Assistants/{AssistantSid}/StyleSheet:
    description: 'TODO: Resource-level docs'
    get:
      description: Returns Style sheet JSON object for this Assistant
      tags:
        - Assistants
        - Sid
        - Assistant
        - Fallback
        - Actions
        - Initiation
        - Dialogues
        - Tasks
        - Task
        - Fields
        - Field
        - Types
        - Type
        - Values
        - Model
        - Builds
        - Queries
        - Samples
        - Style
        - Sheet
    post:
      description: >-
        Updates the style sheet for an assistant identified by {AssistantSid} or
        {AssistantUniqueName}.
      tags:
        - Assistants
        - Sid
        - Assistant
        - Fallback
        - Actions
        - Initiation
        - Dialogues
        - Tasks
        - Task
        - Fields
        - Field
        - Types
        - Type
        - Values
        - Model
        - Builds
        - Queries
        - Samples
        - Style
        - Sheet
  /understand/Assistants/{AssistantSid}/Tasks/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Assistants
        - Sid
        - Assistant
        - Fallback
        - Actions
        - Initiation
        - Dialogues
        - Tasks
        - Task
        - Fields
        - Field
        - Types
        - Type
        - Values
        - Model
        - Builds
        - Queries
        - Samples
        - Style
        - Sheet
    post:
      description: ''
      tags:
        - Assistants
        - Sid
        - Assistant
        - Fallback
        - Actions
        - Initiation
        - Dialogues
        - Tasks
        - Task
        - Fields
        - Field
        - Types
        - Type
        - Values
        - Model
        - Builds
        - Queries
        - Samples
        - Style
        - Sheet
    delete:
      description: ''
      tags:
        - Assistants
        - Sid
        - Assistant
        - Fallback
        - Actions
        - Initiation
        - Dialogues
        - Tasks
        - Task
        - Fields
        - Field
        - Types
        - Type
        - Values
        - Model
        - Builds
        - Queries
        - Samples
        - Style
        - Sheet
  /understand/Assistants/{AssistantSid}/Tasks:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Assistants
        - Sid
        - Assistant
        - Fallback
        - Actions
        - Initiation
        - Dialogues
        - Tasks
        - Task
        - Fields
        - Field
        - Types
        - Type
        - Values
        - Model
        - Builds
        - Queries
        - Samples
        - Style
        - Sheet
    post:
      description: ''
      tags:
        - Assistants
        - Sid
        - Assistant
        - Fallback
        - Actions
        - Initiation
        - Dialogues
        - Tasks
        - Task
        - Fields
        - Field
        - Types
        - Type
        - Values
        - Model
        - Builds
        - Queries
        - Samples
        - Style
        - Sheet
  /understand/Assistants/{AssistantSid}/Tasks/{TaskSid}/Actions:
    description: 'TODO: Resource-level docs'
    get:
      description: Returns JSON actions for this Task.
      tags:
        - Assistants
        - Sid
        - Assistant
        - Fallback
        - Actions
        - Initiation
        - Dialogues
        - Tasks
        - Task
        - Fields
        - Field
        - Types
        - Type
        - Values
        - Model
        - Builds
        - Queries
        - Samples
        - Style
        - Sheet
    post:
      description: >-
        Updates the actions of an Task identified by {TaskSid} or
        {TaskUniqueName}.
      tags:
        - Assistants
        - Sid
        - Assistant
        - Fallback
        - Actions
        - Initiation
        - Dialogues
        - Tasks
        - Task
        - Fields
        - Field
        - Types
        - Type
        - Values
        - Model
        - Builds
        - Queries
        - Samples
        - Style
        - Sheet
  /understand/Assistants/{AssistantSid}/Tasks/{TaskSid}/Statistics:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Assistants
        - Sid
        - Assistant
        - Fallback
        - Actions
        - Initiation
        - Dialogues
        - Tasks
        - Task
        - Fields
        - Field
        - Types
        - Type
        - Values
        - Model
        - Builds
        - Queries
        - Samples
        - Style
        - Sheet
        - Statistics
tags:
  - name: PreviewDeployedDevicesCertificate
  - name: PreviewDeployedDevicesDeployment
  - name: PreviewDeployedDevicesDevice
  - name: PreviewDeployedDevicesFleet
  - name: PreviewDeployedDevicesKey
  - name: PreviewHostedNumbersAuthorizationDocument
  - name: PreviewHostedNumbersDependentHostedNumberOrder
  - name: PreviewHostedNumbersHostedNumberOrder
  - null
  - null
  - null
  - null
  - name: PreviewSyncDocument
  - name: PreviewSyncDocumentPermission
  - name: PreviewSyncService
  - name: PreviewSyncSyncList
  - name: PreviewSyncSyncListItem
  - name: PreviewSyncSyncListPermission
  - name: PreviewSyncSyncMap
  - name: PreviewSyncSyncMapItem
  - name: PreviewSyncSyncMapPermission
  - name: Assistants
  - name: Actions
  - name: Actions
  - name: PreviewUnderstandDialogue
  - name: PreviewUnderstandField
  - name: PreviewUnderstandFieldType
  - name: PreviewUnderstandFieldValue
  - name: PreviewUnderstandModelBuild
  - name: PreviewUnderstandQuery
  - name: PreviewUnderstandSample
  - name: PreviewUnderstandStyleSheet
  - name: PreviewUnderstandTask
  - name: PreviewUnderstandTaskActions
  - name: PreviewUnderstandTaskStatistics
  - name: PreviewWirelessCommand
  - name: PreviewWirelessRatePlan
  - name: PreviewWirelessSim
  - name: PreviewWirelessUsage
x-maturity:
  - name: Preview
    description: >-
      PLEASE NOTE that this is a Preview product that is subject to change. Use
      it with caution. If you currently do not have developer preview access,
      please contact https://www.twilio
