info:
  title: Twilio - Notify
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
openapi: 3.0.1
paths:
  /v1/Services/{ServiceSid}/Bindings/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Bindings
    delete:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Bindings
  /v1/Services/{ServiceSid}/Bindings:
    description: 'TODO: Resource-level docs'
    post:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Bindings
    get:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Bindings
  /v1/Credentials:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Bindings
        - Credentials
    post:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Bindings
        - Credentials
  /v1/Credentials/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Bindings
        - Credentials
    post:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Bindings
        - Credentials
    delete:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Bindings
        - Credentials
  /v1/Services/{ServiceSid}/Notifications:
    description: 'TODO: Resource-level docs'
    post:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Bindings
        - Credentials
        - Notifications
  /v1/Services:
    description: 'TODO: Resource-level docs'
    post:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Bindings
        - Credentials
        - Notifications
    get:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Bindings
        - Credentials
        - Notifications
  /v1/Services/{Sid}:
    description: 'TODO: Resource-level docs'
    delete:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Bindings
        - Credentials
        - Notifications
    get:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Bindings
        - Credentials
        - Notifications
    post:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Bindings
        - Credentials
        - Notifications
tags:
  - name: NotifyV1Binding
  - name: NotifyV1Credential
  - name: NotifyV1Notification
  - name: NotifyV1Service
x-maturity:
  - name: Beta
    description: PLEASE NOTE that this is a Beta product that is subject to change. U
