info:
  title: Twilio - Studio
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
openapi: 3.0.1
paths:
  /v2/Flows/{FlowSid}/Executions:
    description: Executions of Studio flows
    get:
      description: Retrieve a list of all Executions for the Flow.
      tags:
        - Flows
        - Flow
        - Sid
        - Executions
    post:
      description: Triggers a new Execution for the Flow
      tags:
        - Flows
        - Flow
        - Sid
        - Executions
  /v2/Flows/{FlowSid}/Executions/{Sid}:
    description: Executions of Studio flows
    get:
      description: Retrieve an Execution
      tags:
        - Flows
        - Flow
        - Sid
        - Executions
    delete:
      description: Delete the Execution and all Steps relating to it.
      tags:
        - Flows
        - Flow
        - Sid
        - Executions
    post:
      description: Update the status of an Execution to `ended`.
      tags:
        - Flows
        - Flow
        - Sid
        - Executions
  /v2/Flows/{FlowSid}/Executions/{ExecutionSid}/Context:
    description: JSON context for executions
    get:
      description: Retrieve the most recent context for an Execution.
      tags:
        - Flows
        - Flow
        - Sid
        - Executions
        - Execution
        - Context
  /v2/Flows/{FlowSid}/Executions/{ExecutionSid}/Steps:
    description: Individual steps within an execution
    get:
      description: Retrieve a list of all Steps for an Execution.
      tags:
        - Flows
        - Flow
        - Sid
        - Executions
        - Execution
        - Context
        - Steps
  /v2/Flows/{FlowSid}/Executions/{ExecutionSid}/Steps/{Sid}:
    description: Individual steps within an execution
    get:
      description: Retrieve a Step.
      tags:
        - Flows
        - Flow
        - Sid
        - Executions
        - Execution
        - Context
        - Steps
  /v2/Flows/{FlowSid}/Executions/{ExecutionSid}/Steps/{StepSid}/Context:
    description: JSON context for an individual step within an execution
    get:
      description: Retrieve the context for an Execution Step.
      tags:
        - Flows
        - Flow
        - Sid
        - Executions
        - Execution
        - Context
        - Steps
        - Step
  /v2/Flows:
    description: Studio flows
    post:
      description: Create a Flow.
      tags:
        - Flows
        - Flow
        - Sid
        - Executions
        - Execution
        - Context
        - Steps
        - Step
    get:
      description: Retrieve a list of all Flows.
      tags:
        - Flows
        - Flow
        - Sid
        - Executions
        - Execution
        - Context
        - Steps
        - Step
  /v2/Flows/{Sid}:
    description: Studio flows
    post:
      description: Update a Flow.
      tags:
        - Flows
        - Flow
        - Sid
        - Executions
        - Execution
        - Context
        - Steps
        - Step
    get:
      description: Retrieve a specific Flow.
      tags:
        - Flows
        - Flow
        - Sid
        - Executions
        - Execution
        - Context
        - Steps
        - Step
    delete:
      description: Delete a specific Flow.
      tags:
        - Flows
        - Flow
        - Sid
        - Executions
        - Execution
        - Context
        - Steps
        - Step
  /v2/Flows/{Sid}/Revisions:
    description: Studio flows revisions
    get:
      description: Retrieve a list of all Flows revisions.
      tags:
        - Flows
        - Flow
        - Sid
        - Executions
        - Execution
        - Context
        - Steps
        - Step
        - Revisions
  /v2/Flows/{Sid}/Revisions/{Revision}:
    description: Studio flows revisions
    get:
      description: Retrieve a specific Flow revision.
      tags:
        - Flows
        - Flow
        - Sid
        - Executions
        - Execution
        - Context
        - Steps
        - Step
        - Revisions
        - Revision
  /v2/Flows/Validate:
    description: Flow definition validator
    post:
      description: Validate flow JSON definition
      tags:
        - Flows
        - Flow
        - Sid
        - Executions
        - Execution
        - Context
        - Steps
        - Step
        - Revisions
        - Revision
        - Validate
  /v2/Flows/{Sid}/TestUsers:
    description: Test users of a flow
    get:
      description: Fetch flow test users
      tags:
        - Flows
        - Flow
        - Sid
        - Executions
        - Execution
        - Context
        - Steps
        - Step
        - Revisions
        - Revision
        - Validate
        - Test
        - Users
    post:
      description: Update flow test users
      tags:
        - Flows
        - Flow
        - Sid
        - Executions
        - Execution
        - Context
        - Steps
        - Step
        - Revisions
        - Revision
        - Validate
        - Test
        - Users
tags:
  - name: StudioV2Execution
  - name: StudioV2ExecutionContext
  - name: StudioV2ExecutionStep
  - name: StudioV2ExecutionStepContext
  - name: StudioV2Flow
  - name: StudioV2FlowRevision
  - name: StudioV2FlowTestUser
  - name: StudioV2FlowValidate
x-maturity:
  - name: GA
    description: This product is G
