info:
  title: Twilio - Sync
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
openapi: 3.0.1
paths:
  /v1/Services/{ServiceSid}/Documents/{Sid}:
    description: Sync Document objects
    get:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Documents
    delete:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Documents
    post:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Documents
  /v1/Services/{ServiceSid}/Documents:
    description: Sync Document objects
    post:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Documents
    get:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Documents
  /v1/Services/{ServiceSid}/Documents/{DocumentSid}/Permissions/{Identity}:
    description: Sync document permissions
    get:
      description: Fetch a specific Sync Document Permission.
      tags:
        - Services
        - Service
        - Sid
        - Documents
        - Document
        - Permissions
        - Identity
    delete:
      description: Delete a specific Sync Document Permission.
      tags:
        - Services
        - Service
        - Sid
        - Documents
        - Document
        - Permissions
        - Identity
    post:
      description: Update an identity's access to a specific Sync Document.
      tags:
        - Services
        - Service
        - Sid
        - Documents
        - Document
        - Permissions
        - Identity
  /v1/Services/{ServiceSid}/Documents/{DocumentSid}/Permissions:
    description: Sync document permissions
    get:
      description: Retrieve a list of all Permissions applying to a Sync Document.
      tags:
        - Services
        - Service
        - Sid
        - Documents
        - Document
        - Permissions
        - Identity
  /v1/Services/{Sid}:
    description: Containers for sync objects
    get:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Documents
        - Document
        - Permissions
        - Identity
    delete:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Documents
        - Document
        - Permissions
        - Identity
    post:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Documents
        - Document
        - Permissions
        - Identity
  /v1/Services:
    description: Containers for sync objects
    post:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Documents
        - Document
        - Permissions
        - Identity
    get:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Documents
        - Document
        - Permissions
        - Identity
  /v1/Services/{ServiceSid}/Streams/{StreamSid}/Messages:
    description: 'TODO: Resource-level docs'
    post:
      description: Create a new Stream Message.
      tags:
        - Services
        - Service
        - Sid
        - Documents
        - Document
        - Permissions
        - Identity
        - Streams
        - Stream
        - Messages
  /v1/Services/{ServiceSid}/Lists/{Sid}:
    description: Sync list objects
    get:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Documents
        - Document
        - Permissions
        - Identity
        - Streams
        - Stream
        - Messages
        - Lists
    delete:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Documents
        - Document
        - Permissions
        - Identity
        - Streams
        - Stream
        - Messages
        - Lists
    post:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Documents
        - Document
        - Permissions
        - Identity
        - Streams
        - Stream
        - Messages
        - Lists
  /v1/Services/{ServiceSid}/Lists:
    description: Sync list objects
    post:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Documents
        - Document
        - Permissions
        - Identity
        - Streams
        - Stream
        - Messages
        - Lists
    get:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Documents
        - Document
        - Permissions
        - Identity
        - Streams
        - Stream
        - Messages
        - Lists
  /v1/Services/{ServiceSid}/Lists/{ListSid}/Items/{Index}:
    description: Items in a sync list
    get:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Documents
        - Document
        - Permissions
        - Identity
        - Streams
        - Stream
        - Messages
        - Lists
        - List
        - Items
        - Index
    delete:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Documents
        - Document
        - Permissions
        - Identity
        - Streams
        - Stream
        - Messages
        - Lists
        - List
        - Items
        - Index
    post:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Documents
        - Document
        - Permissions
        - Identity
        - Streams
        - Stream
        - Messages
        - Lists
        - List
        - Items
        - Index
  /v1/Services/{ServiceSid}/Lists/{ListSid}/Items:
    description: Items in a sync list
    post:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Documents
        - Document
        - Permissions
        - Identity
        - Streams
        - Stream
        - Messages
        - Lists
        - List
        - Items
        - Index
    get:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Documents
        - Document
        - Permissions
        - Identity
        - Streams
        - Stream
        - Messages
        - Lists
        - List
        - Items
        - Index
  /v1/Services/{ServiceSid}/Lists/{ListSid}/Permissions/{Identity}:
    description: Permissions for Sync list items
    get:
      description: Fetch a specific Sync List Permission.
      tags:
        - Services
        - Service
        - Sid
        - Documents
        - Document
        - Permissions
        - Identity
        - Streams
        - Stream
        - Messages
        - Lists
        - List
        - Items
        - Index
    delete:
      description: Delete a specific Sync List Permission.
      tags:
        - Services
        - Service
        - Sid
        - Documents
        - Document
        - Permissions
        - Identity
        - Streams
        - Stream
        - Messages
        - Lists
        - List
        - Items
        - Index
    post:
      description: Update an identity's access to a specific Sync List.
      tags:
        - Services
        - Service
        - Sid
        - Documents
        - Document
        - Permissions
        - Identity
        - Streams
        - Stream
        - Messages
        - Lists
        - List
        - Items
        - Index
  /v1/Services/{ServiceSid}/Lists/{ListSid}/Permissions:
    description: Permissions for Sync list items
    get:
      description: Retrieve a list of all Permissions applying to a Sync List.
      tags:
        - Services
        - Service
        - Sid
        - Documents
        - Document
        - Permissions
        - Identity
        - Streams
        - Stream
        - Messages
        - Lists
        - List
        - Items
        - Index
  /v1/Services/{ServiceSid}/Maps/{Sid}:
    description: Sync map objects
    get:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Documents
        - Document
        - Permissions
        - Identity
        - Streams
        - Stream
        - Messages
        - Lists
        - List
        - Items
        - Index
        - Maps
    delete:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Documents
        - Document
        - Permissions
        - Identity
        - Streams
        - Stream
        - Messages
        - Lists
        - List
        - Items
        - Index
        - Maps
    post:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Documents
        - Document
        - Permissions
        - Identity
        - Streams
        - Stream
        - Messages
        - Lists
        - List
        - Items
        - Index
        - Maps
  /v1/Services/{ServiceSid}/Maps:
    description: Sync map objects
    post:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Documents
        - Document
        - Permissions
        - Identity
        - Streams
        - Stream
        - Messages
        - Lists
        - List
        - Items
        - Index
        - Maps
    get:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Documents
        - Document
        - Permissions
        - Identity
        - Streams
        - Stream
        - Messages
        - Lists
        - List
        - Items
        - Index
        - Maps
  /v1/Services/{ServiceSid}/Maps/{MapSid}/Items/{Key}:
    description: Keys in a sync map
    get:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Documents
        - Document
        - Permissions
        - Identity
        - Streams
        - Stream
        - Messages
        - Lists
        - List
        - Items
        - Index
        - Maps
        - Map
        - Key
    delete:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Documents
        - Document
        - Permissions
        - Identity
        - Streams
        - Stream
        - Messages
        - Lists
        - List
        - Items
        - Index
        - Maps
        - Map
        - Key
    post:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Documents
        - Document
        - Permissions
        - Identity
        - Streams
        - Stream
        - Messages
        - Lists
        - List
        - Items
        - Index
        - Maps
        - Map
        - Key
  /v1/Services/{ServiceSid}/Maps/{MapSid}/Items:
    description: Keys in a sync map
    post:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Documents
        - Document
        - Permissions
        - Identity
        - Streams
        - Stream
        - Messages
        - Lists
        - List
        - Items
        - Index
        - Maps
        - Map
        - Key
    get:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Documents
        - Document
        - Permissions
        - Identity
        - Streams
        - Stream
        - Messages
        - Lists
        - List
        - Items
        - Index
        - Maps
        - Map
        - Key
  /v1/Services/{ServiceSid}/Maps/{MapSid}/Permissions/{Identity}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch a specific Sync Map Permission.
      tags:
        - Services
        - Service
        - Sid
        - Documents
        - Document
        - Permissions
        - Identity
        - Streams
        - Stream
        - Messages
        - Lists
        - List
        - Items
        - Index
        - Maps
        - Map
        - Key
    delete:
      description: Delete a specific Sync Map Permission.
      tags:
        - Services
        - Service
        - Sid
        - Documents
        - Document
        - Permissions
        - Identity
        - Streams
        - Stream
        - Messages
        - Lists
        - List
        - Items
        - Index
        - Maps
        - Map
        - Key
    post:
      description: Update an identity's access to a specific Sync Map.
      tags:
        - Services
        - Service
        - Sid
        - Documents
        - Document
        - Permissions
        - Identity
        - Streams
        - Stream
        - Messages
        - Lists
        - List
        - Items
        - Index
        - Maps
        - Map
        - Key
  /v1/Services/{ServiceSid}/Maps/{MapSid}/Permissions:
    description: 'TODO: Resource-level docs'
    get:
      description: Retrieve a list of all Permissions applying to a Sync Map.
      tags:
        - Services
        - Service
        - Sid
        - Documents
        - Document
        - Permissions
        - Identity
        - Streams
        - Stream
        - Messages
        - Lists
        - List
        - Items
        - Index
        - Maps
        - Map
        - Key
  /v1/Services/{ServiceSid}/Streams/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch a specific Stream.
      tags:
        - Services
        - Service
        - Sid
        - Documents
        - Document
        - Permissions
        - Identity
        - Streams
        - Stream
        - Messages
        - Lists
        - List
        - Items
        - Index
        - Maps
        - Map
        - Key
    delete:
      description: Delete a specific Stream.
      tags:
        - Services
        - Service
        - Sid
        - Documents
        - Document
        - Permissions
        - Identity
        - Streams
        - Stream
        - Messages
        - Lists
        - List
        - Items
        - Index
        - Maps
        - Map
        - Key
    post:
      description: Update a specific Stream.
      tags:
        - Services
        - Service
        - Sid
        - Documents
        - Document
        - Permissions
        - Identity
        - Streams
        - Stream
        - Messages
        - Lists
        - List
        - Items
        - Index
        - Maps
        - Map
        - Key
  /v1/Services/{ServiceSid}/Streams:
    description: 'TODO: Resource-level docs'
    post:
      description: Create a new Stream.
      tags:
        - Services
        - Service
        - Sid
        - Documents
        - Document
        - Permissions
        - Identity
        - Streams
        - Stream
        - Messages
        - Lists
        - List
        - Items
        - Index
        - Maps
        - Map
        - Key
    get:
      description: Retrieve a list of all Streams in a Service Instance.
      tags:
        - Services
        - Service
        - Sid
        - Documents
        - Document
        - Permissions
        - Identity
        - Streams
        - Stream
        - Messages
        - Lists
        - List
        - Items
        - Index
        - Maps
        - Map
        - Key
tags:
  - name: SyncV1Document
  - name: SyncV1DocumentPermission
  - name: SyncV1Service
  - name: SyncV1StreamMessage
  - name: SyncV1SyncList
  - name: SyncV1SyncListItem
  - name: SyncV1SyncListPermission
  - name: SyncV1SyncMap
  - name: SyncV1SyncMapItem
  - name: SyncV1SyncMapPermission
  - name: SyncV1SyncStream
x-maturity:
  - name: GA
    description: This product is G
