info:
  title: Twilio - Trunking
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
openapi: 3.0.1
paths:
  /v1/Trunks/{TrunkSid}/CredentialLists/{Sid}:
    description: List of credentials for accessing a trunk
    get:
      description: ''
      tags:
        - Trunks
        - Trunk
        - Sid
        - Credential
        - Lists
    delete:
      description: ''
      tags:
        - Trunks
        - Trunk
        - Sid
        - Credential
        - Lists
  /v1/Trunks/{TrunkSid}/CredentialLists:
    description: List of credentials for accessing a trunk
    post:
      description: ''
      tags:
        - Trunks
        - Trunk
        - Sid
        - Credential
        - Lists
    get:
      description: ''
      tags:
        - Trunks
        - Trunk
        - Sid
        - Credential
        - Lists
  /v1/Trunks/{TrunkSid}/IpAccessControlLists/{Sid}:
    description: List of IP addresses for accessing a trunk
    get:
      description: ''
      tags:
        - Trunks
        - Trunk
        - Sid
        - Credential
        - Lists
        - Ip
        - Access
        - Control
    delete:
      description: Remove an associated IP Access Control List from a Trunk
      tags:
        - Trunks
        - Trunk
        - Sid
        - Credential
        - Lists
        - Ip
        - Access
        - Control
  /v1/Trunks/{TrunkSid}/IpAccessControlLists:
    description: List of IP addresses for accessing a trunk
    post:
      description: Associate an IP Access Control List with a Trunk
      tags:
        - Trunks
        - Trunk
        - Sid
        - Credential
        - Lists
        - Ip
        - Access
        - Control
    get:
      description: List all IP Access Control Lists for a Trunk
      tags:
        - Trunks
        - Trunk
        - Sid
        - Credential
        - Lists
        - Ip
        - Access
        - Control
  /v1/Trunks/{TrunkSid}/OriginationUrls/{Sid}:
    description: Network element entry points into your communications infrastructure
    get:
      description: ''
      tags:
        - Trunks
        - Trunk
        - Sid
        - Credential
        - Lists
        - Ip
        - Access
        - Control
        - Origination
        - Urls
    delete:
      description: ''
      tags:
        - Trunks
        - Trunk
        - Sid
        - Credential
        - Lists
        - Ip
        - Access
        - Control
        - Origination
        - Urls
    post:
      description: ''
      tags:
        - Trunks
        - Trunk
        - Sid
        - Credential
        - Lists
        - Ip
        - Access
        - Control
        - Origination
        - Urls
  /v1/Trunks/{TrunkSid}/OriginationUrls:
    description: Network element entry points into your communications infrastructure
    post:
      description: ''
      tags:
        - Trunks
        - Trunk
        - Sid
        - Credential
        - Lists
        - Ip
        - Access
        - Control
        - Origination
        - Urls
    get:
      description: ''
      tags:
        - Trunks
        - Trunk
        - Sid
        - Credential
        - Lists
        - Ip
        - Access
        - Control
        - Origination
        - Urls
  /v1/Trunks/{TrunkSid}/PhoneNumbers/{Sid}:
    description: Phone numbers associated with trunks
    get:
      description: ''
      tags:
        - Trunks
        - Trunk
        - Sid
        - Credential
        - Lists
        - Ip
        - Access
        - Control
        - Origination
        - Urls
        - Phone
        - Numbers
    delete:
      description: ''
      tags:
        - Trunks
        - Trunk
        - Sid
        - Credential
        - Lists
        - Ip
        - Access
        - Control
        - Origination
        - Urls
        - Phone
        - Numbers
  /v1/Trunks/{TrunkSid}/PhoneNumbers:
    description: Phone numbers associated with trunks
    post:
      description: ''
      tags:
        - Trunks
        - Trunk
        - Sid
        - Credential
        - Lists
        - Ip
        - Access
        - Control
        - Origination
        - Urls
        - Phone
        - Numbers
    get:
      description: ''
      tags:
        - Trunks
        - Trunk
        - Sid
        - Credential
        - Lists
        - Ip
        - Access
        - Control
        - Origination
        - Urls
        - Phone
        - Numbers
  /v1/Trunks/{TrunkSid}/Recording:
    description: Recording settings for a trunk
    get:
      description: ''
      tags:
        - Trunks
        - Trunk
        - Sid
        - Credential
        - Lists
        - Ip
        - Access
        - Control
        - Origination
        - Urls
        - Phone
        - Numbers
        - Recording
    post:
      description: ''
      tags:
        - Trunks
        - Trunk
        - Sid
        - Credential
        - Lists
        - Ip
        - Access
        - Control
        - Origination
        - Urls
        - Phone
        - Numbers
        - Recording
  /v1/Trunks/{Sid}:
    description: Represents a SIP trunk
    get:
      description: ''
      tags:
        - Trunks
        - Trunk
        - Sid
        - Credential
        - Lists
        - Ip
        - Access
        - Control
        - Origination
        - Urls
        - Phone
        - Numbers
        - Recording
    delete:
      description: ''
      tags:
        - Trunks
        - Trunk
        - Sid
        - Credential
        - Lists
        - Ip
        - Access
        - Control
        - Origination
        - Urls
        - Phone
        - Numbers
        - Recording
    post:
      description: ''
      tags:
        - Trunks
        - Trunk
        - Sid
        - Credential
        - Lists
        - Ip
        - Access
        - Control
        - Origination
        - Urls
        - Phone
        - Numbers
        - Recording
  /v1/Trunks:
    description: Represents a SIP trunk
    post:
      description: ''
      tags:
        - Trunks
        - Trunk
        - Sid
        - Credential
        - Lists
        - Ip
        - Access
        - Control
        - Origination
        - Urls
        - Phone
        - Numbers
        - Recording
    get:
      description: ''
      tags:
        - Trunks
        - Trunk
        - Sid
        - Credential
        - Lists
        - Ip
        - Access
        - Control
        - Origination
        - Urls
        - Phone
        - Numbers
        - Recording
tags:
  - name: TrunkingV1CredentialList
  - name: TrunkingV1IpAccessControlList
  - name: TrunkingV1OriginationUrl
  - name: TrunkingV1PhoneNumber
  - name: TrunkingV1Recording
  - name: TrunkingV1Trunk
x-maturity:
  - name: GA
    description: This product is G
