info:
  title: Twilio - Voice
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
openapi: 3.0.1
paths:
  /v1/Archives/{Date}/Calls/{Sid}:
    description: 'TODO: Resource-level docs'
    delete:
      description: >-
        Delete an archived call record from Bulk Export. Note: this does not
        also delete the record from the Voice API.
      tags:
        - Archives
        - Date
        - Calls
        - Sid
  /v1/ByocTrunks:
    description: >-
      BYOC Trunks allow you to bring your own voice carrier to Twilio, enabling
      your calls to use our Programmable Voice APIs.
    post:
      description: ''
      tags:
        - Archives
        - Date
        - Calls
        - Sid
        - Byoc
        - Trunks
    get:
      description: ''
      tags:
        - Archives
        - Date
        - Calls
        - Sid
        - Byoc
        - Trunks
  /v1/ByocTrunks/{Sid}:
    description: >-
      BYOC Trunks allow you to bring your own voice carrier to Twilio, enabling
      your calls to use our Programmable Voice APIs.
    get:
      description: ''
      tags:
        - Archives
        - Date
        - Calls
        - Sid
        - Byoc
        - Trunks
    post:
      description: ''
      tags:
        - Archives
        - Date
        - Calls
        - Sid
        - Byoc
        - Trunks
    delete:
      description: ''
      tags:
        - Archives
        - Date
        - Calls
        - Sid
        - Byoc
        - Trunks
  /v1/ConnectionPolicies:
    description: >-
      Connection Policy for sending traffic to your communications
      infrastructure.
    post:
      description: ''
      tags:
        - Archives
        - Date
        - Calls
        - Sid
        - Byoc
        - Trunks
        - Connection
        - Policies
    get:
      description: ''
      tags:
        - Archives
        - Date
        - Calls
        - Sid
        - Byoc
        - Trunks
        - Connection
        - Policies
  /v1/ConnectionPolicies/{Sid}:
    description: >-
      Connection Policy for sending traffic to your communications
      infrastructure.
    get:
      description: ''
      tags:
        - Archives
        - Date
        - Calls
        - Sid
        - Byoc
        - Trunks
        - Connection
        - Policies
    post:
      description: ''
      tags:
        - Archives
        - Date
        - Calls
        - Sid
        - Byoc
        - Trunks
        - Connection
        - Policies
    delete:
      description: ''
      tags:
        - Archives
        - Date
        - Calls
        - Sid
        - Byoc
        - Trunks
        - Connection
        - Policies
  /v1/ConnectionPolicies/{ConnectionPolicySid}/Targets:
    description: Network element entry points into your communications infrastructure
    post:
      description: ''
      tags:
        - Archives
        - Date
        - Calls
        - Sid
        - Byoc
        - Trunks
        - Connection
        - Policies
        - Policy
        - Targets
    get:
      description: ''
      tags:
        - Archives
        - Date
        - Calls
        - Sid
        - Byoc
        - Trunks
        - Connection
        - Policies
        - Policy
        - Targets
  /v1/ConnectionPolicies/{ConnectionPolicySid}/Targets/{Sid}:
    description: Network element entry points into your communications infrastructure
    get:
      description: ''
      tags:
        - Archives
        - Date
        - Calls
        - Sid
        - Byoc
        - Trunks
        - Connection
        - Policies
        - Policy
        - Targets
    post:
      description: ''
      tags:
        - Archives
        - Date
        - Calls
        - Sid
        - Byoc
        - Trunks
        - Connection
        - Policies
        - Policy
        - Targets
    delete:
      description: ''
      tags:
        - Archives
        - Date
        - Calls
        - Sid
        - Byoc
        - Trunks
        - Connection
        - Policies
        - Policy
        - Targets
  /v1/DialingPermissions:
    description: 'TODO: Resource-level docs'
  /v1/DialingPermissions/Countries/{IsoCode}:
    description: 'TODO: Resource-level docs'
    get:
      description: >-
        Retrieve voice dialing country permissions identified by the given ISO
        country code
      tags:
        - Archives
        - Date
        - Calls
        - Sid
        - Byoc
        - Trunks
        - Connection
        - Policies
        - Policy
        - Targets
        - Dialing
        - Permissions
        - Countries
        - Iso
        - Code
  /v1/DialingPermissions/Countries:
    description: 'TODO: Resource-level docs'
    get:
      description: Retrieve all voice dialing country permissions for this account
      tags:
        - Archives
        - Date
        - Calls
        - Sid
        - Byoc
        - Trunks
        - Connection
        - Policies
        - Policy
        - Targets
        - Dialing
        - Permissions
        - Countries
        - Iso
        - Code
  /v1/DialingPermissions/BulkCountryUpdates:
    description: 'TODO: Resource-level docs'
    post:
      description: >-
        Create a bulk update request to change voice dialing country permissions
        of one or more countries identified by the corresponding [ISO country
        code](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2)
      tags:
        - Archives
        - Date
        - Calls
        - Sid
        - Byoc
        - Trunks
        - Connection
        - Policies
        - Policy
        - Targets
        - Dialing
        - Permissions
        - Countries
        - Iso
        - Code
        - Bulk
        - Country
        - Updates
  /v1/DialingPermissions/Countries/{IsoCode}/HighRiskSpecialPrefixes:
    description: 'TODO: Resource-level docs'
    get:
      description: >-
        Fetch the high-risk special services prefixes from the country resource
        corresponding to the [ISO country
        code](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2)
      tags:
        - Archives
        - Date
        - Calls
        - Sid
        - Byoc
        - Trunks
        - Connection
        - Policies
        - Policy
        - Targets
        - Dialing
        - Permissions
        - Countries
        - Iso
        - Code
        - Bulk
        - Country
        - Updates
        - High
        - Risk
        - Special
        - Prefixes
  /v1/Settings:
    description: 'TODO: Resource-level docs'
    get:
      description: Retrieve voice dialing permissions inheritance for the sub-account
      tags:
        - Archives
        - Date
        - Calls
        - Sid
        - Byoc
        - Trunks
        - Connection
        - Policies
        - Policy
        - Targets
        - Dialing
        - Permissions
        - Countries
        - Iso
        - Code
        - Bulk
        - Country
        - Updates
        - High
        - Risk
        - Special
        - Prefixes
        - Settings
    post:
      description: Update voice dialing permissions inheritance for the sub-account
      tags:
        - Archives
        - Date
        - Calls
        - Sid
        - Byoc
        - Trunks
        - Connection
        - Policies
        - Policy
        - Targets
        - Dialing
        - Permissions
        - Countries
        - Iso
        - Code
        - Bulk
        - Country
        - Updates
        - High
        - Risk
        - Special
        - Prefixes
        - Settings
  /v1/IpRecords:
    description: >-
      IP Records hold information about the IP addresses and ranges
      ([CIDR](https://tools.ietf.org/html/rfc4632) blocks) that your traffic
      will be associated with.
    post:
      description: ''
      tags:
        - Archives
        - Date
        - Calls
        - Sid
        - Byoc
        - Trunks
        - Connection
        - Policies
        - Policy
        - Targets
        - Dialing
        - Permissions
        - Countries
        - Iso
        - Code
        - Bulk
        - Country
        - Updates
        - High
        - Risk
        - Special
        - Prefixes
        - Settings
        - Ip
        - Records
    get:
      description: ''
      tags:
        - Archives
        - Date
        - Calls
        - Sid
        - Byoc
        - Trunks
        - Connection
        - Policies
        - Policy
        - Targets
        - Dialing
        - Permissions
        - Countries
        - Iso
        - Code
        - Bulk
        - Country
        - Updates
        - High
        - Risk
        - Special
        - Prefixes
        - Settings
        - Ip
        - Records
  /v1/IpRecords/{Sid}:
    description: >-
      IP Records hold information about the IP addresses and ranges
      ([CIDR](https://tools.ietf.org/html/rfc4632) blocks) that your traffic
      will be associated with.
    get:
      description: ''
      tags:
        - Archives
        - Date
        - Calls
        - Sid
        - Byoc
        - Trunks
        - Connection
        - Policies
        - Policy
        - Targets
        - Dialing
        - Permissions
        - Countries
        - Iso
        - Code
        - Bulk
        - Country
        - Updates
        - High
        - Risk
        - Special
        - Prefixes
        - Settings
        - Ip
        - Records
    post:
      description: ''
      tags:
        - Archives
        - Date
        - Calls
        - Sid
        - Byoc
        - Trunks
        - Connection
        - Policies
        - Policy
        - Targets
        - Dialing
        - Permissions
        - Countries
        - Iso
        - Code
        - Bulk
        - Country
        - Updates
        - High
        - Risk
        - Special
        - Prefixes
        - Settings
        - Ip
        - Records
    delete:
      description: ''
      tags:
        - Archives
        - Date
        - Calls
        - Sid
        - Byoc
        - Trunks
        - Connection
        - Policies
        - Policy
        - Targets
        - Dialing
        - Permissions
        - Countries
        - Iso
        - Code
        - Bulk
        - Country
        - Updates
        - High
        - Risk
        - Special
        - Prefixes
        - Settings
        - Ip
        - Records
  /v1/SourceIpMappings:
    description: >-
      With Source IP Mappings, Twilio can recognize your SIP requests based on
      where they are sent from. The Request-URI no longer has to have the FQDN
      (Fully Qualified Domain Name) of your SIP Domain.
    post:
      description: ''
      tags:
        - Archives
        - Date
        - Calls
        - Sid
        - Byoc
        - Trunks
        - Connection
        - Policies
        - Policy
        - Targets
        - Dialing
        - Permissions
        - Countries
        - Iso
        - Code
        - Bulk
        - Country
        - Updates
        - High
        - Risk
        - Special
        - Prefixes
        - Settings
        - Ip
        - Records
        - Source
        - Mappings
    get:
      description: ''
      tags:
        - Archives
        - Date
        - Calls
        - Sid
        - Byoc
        - Trunks
        - Connection
        - Policies
        - Policy
        - Targets
        - Dialing
        - Permissions
        - Countries
        - Iso
        - Code
        - Bulk
        - Country
        - Updates
        - High
        - Risk
        - Special
        - Prefixes
        - Settings
        - Ip
        - Records
        - Source
        - Mappings
  /v1/SourceIpMappings/{Sid}:
    description: >-
      With Source IP Mappings, Twilio can recognize your SIP requests based on
      where they are sent from. The Request-URI no longer has to have the FQDN
      (Fully Qualified Domain Name) of your SIP Domain.
    get:
      description: ''
      tags:
        - Archives
        - Date
        - Calls
        - Sid
        - Byoc
        - Trunks
        - Connection
        - Policies
        - Policy
        - Targets
        - Dialing
        - Permissions
        - Countries
        - Iso
        - Code
        - Bulk
        - Country
        - Updates
        - High
        - Risk
        - Special
        - Prefixes
        - Settings
        - Ip
        - Records
        - Source
        - Mappings
    post:
      description: ''
      tags:
        - Archives
        - Date
        - Calls
        - Sid
        - Byoc
        - Trunks
        - Connection
        - Policies
        - Policy
        - Targets
        - Dialing
        - Permissions
        - Countries
        - Iso
        - Code
        - Bulk
        - Country
        - Updates
        - High
        - Risk
        - Special
        - Prefixes
        - Settings
        - Ip
        - Records
        - Source
        - Mappings
    delete:
      description: ''
      tags:
        - Archives
        - Date
        - Calls
        - Sid
        - Byoc
        - Trunks
        - Connection
        - Policies
        - Policy
        - Targets
        - Dialing
        - Permissions
        - Countries
        - Iso
        - Code
        - Bulk
        - Country
        - Updates
        - High
        - Risk
        - Special
        - Prefixes
        - Settings
        - Ip
        - Records
        - Source
        - Mappings
tags:
  - name: VoiceV1ArchivedCall
  - name: VoiceV1BulkCountryUpdate
  - name: VoiceV1ByocTrunk
  - name: VoiceV1ConnectionPolicy
  - name: VoiceV1ConnectionPolicyTarget
  - name: VoiceV1Country
  - name: VoiceV1HighriskSpecialPrefix
  - name: VoiceV1IpRecord
  - name: VoiceV1Settings
  - name: VoiceV1SourceIpMapping
x-maturity:
  - name: GA
    description: This product is Generally Available.
  - name: Beta
    description: >-
      PLEASE NOTE that this is a Beta product that is subject to change. Use it
      with caution.
  - name: Preview
    description: >-
      PLEASE NOTE that this is a Preview product that is subject to change. Use
      it with caution. If you currently do not have developer preview access,
      please contact https://www.twilio
