info:
  title: Twilio - Wireless
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
openapi: 3.0.1
paths:
  /v1/UsageRecords:
    description: Aggregated Usage information for all SIMs on an Account
    get:
      description: ''
      tags:
        - Usage
        - Records
  /v1/Commands/{Sid}:
    description: Machine-to-machine commands sent to/from devices
    get:
      description: Fetch a Command instance from your account.
      tags:
        - Usage
        - Records
        - Commands
        - Sid
    delete:
      description: Delete a Command instance from your account.
      tags:
        - Usage
        - Records
        - Commands
        - Sid
  /v1/Commands:
    description: Machine-to-machine commands sent to/from devices
    get:
      description: Retrieve a list of Commands from your account.
      tags:
        - Usage
        - Records
        - Commands
        - Sid
    post:
      description: Send a Command to a Sim.
      tags:
        - Usage
        - Records
        - Commands
        - Sid
  /v1/Sims/{SimSid}/DataSessions:
    description: Data session information for SIMs
    get:
      description: ''
      tags:
        - Usage
        - Records
        - Commands
        - Sid
        - Sims
        - Sim
        - Data
        - Sessions
  /v1/RatePlans:
    description: Capabilities and restrictions for SIMs
    get:
      description: ''
      tags:
        - Usage
        - Records
        - Commands
        - Sid
        - Sims
        - Sim
        - Data
        - Sessions
        - Rate
        - Plans
    post:
      description: ''
      tags:
        - Usage
        - Records
        - Commands
        - Sid
        - Sims
        - Sim
        - Data
        - Sessions
        - Rate
        - Plans
  /v1/RatePlans/{Sid}:
    description: Capabilities and restrictions for SIMs
    get:
      description: ''
      tags:
        - Usage
        - Records
        - Commands
        - Sid
        - Sims
        - Sim
        - Data
        - Sessions
        - Rate
        - Plans
    post:
      description: ''
      tags:
        - Usage
        - Records
        - Commands
        - Sid
        - Sims
        - Sim
        - Data
        - Sessions
        - Rate
        - Plans
    delete:
      description: ''
      tags:
        - Usage
        - Records
        - Commands
        - Sid
        - Sims
        - Sim
        - Data
        - Sessions
        - Rate
        - Plans
  /v1/Sims/{Sid}:
    description: A resource representing a Programmable Wireless SIM
    get:
      description: Fetch a Sim resource on your Account.
      tags:
        - Usage
        - Records
        - Commands
        - Sid
        - Sims
        - Sim
        - Data
        - Sessions
        - Rate
        - Plans
    post:
      description: Updates the given properties of a Sim resource on your Account.
      tags:
        - Usage
        - Records
        - Commands
        - Sid
        - Sims
        - Sim
        - Data
        - Sessions
        - Rate
        - Plans
    delete:
      description: Delete a Sim resource on your Account.
      tags:
        - Usage
        - Records
        - Commands
        - Sid
        - Sims
        - Sim
        - Data
        - Sessions
        - Rate
        - Plans
  /v1/Sims:
    description: A resource representing a Programmable Wireless SIM
    get:
      description: Retrieve a list of Sim resources on your Account.
      tags:
        - Usage
        - Records
        - Commands
        - Sid
        - Sims
        - Sim
        - Data
        - Sessions
        - Rate
        - Plans
  /v1/Sims/{SimSid}/UsageRecords:
    description: Usage information for SIMs
    get:
      description: ''
      tags:
        - Usage
        - Records
        - Commands
        - Sid
        - Sims
        - Sim
        - Data
        - Sessions
        - Rate
        - Plans
tags:
  - name: WirelessV1Command
  - name: WirelessV1DataSession
  - name: WirelessV1RatePlan
  - name: WirelessV1Sim
  - name: WirelessV1UsageRecord
x-maturity:
  - name: GA
    description: This product is G
